BIRMINGHAM_COMMUNITIES = ["Glen Iris - CUSTOM", 
               "Hamptons", 
               "Kirkman", 
               "Magnolia", 
               "Riverwoods - CUSTOM", 
               "Sawyer Trail",
               "Stockton"]

NASHVILLE_COMMUNITIES = ["Brenley Crossing",
               "Carothers Cove",
               "Cromwell",
               "Enderly Pointe",
               "Jackson Hills"]

BIRMINGHAM_BUILDERS = ["Adam Goodwin",
            "Allen Sandlin",
            "Bill Cleckley",
            "Brian Henderson",
            "Bryan Shirley",
            "Chris Williams",
            "Daniel Hill",
            "Denson Dean",
            "Doug Hill",
            "Greg Byrd",
            "Henry Williams",
            "Jaye Watts",
            "Jody Bowlin",
            "John Lowery",
            "Jon Clement",
            "Josh Brasher",
            "Ryan Dempsey",
            "Sam Russell",
            "Terry Franklin",
            "Wayne Black",
            "Wil Sullivan"]

NASHVILLE_BUILDERS = ["Bill Russell",
            "Brad Ivey",
            "Eric Comer",
            "Erick Waldon",
            "Jeff Yocca",
            "Kerry Beason",
            "Nick Bateman"]

BIRMINGHAM_SUPPLIERS = [
"1st Impressions Residential Cleaning",
"3 Way Cleaning Company, LLC",
"84 Lumber",
"84 Lumber***FRAMING***",
"A H Plumbing, LLC",
"ABC Cutting Construction, Inc/Bessemer",
"Acme Brick/Jenkins Brick Company",
"AFD Construction, LLC",
"Alabama Engineering Company, Inc",
"Alabama Fireplace & Construction Specialties, LLC",
"Alabama Mailbox Co. LLC",
"Alabama Wholesale Stone, Inc.",
"Alfredo's Painting and Drywall",
"Allsouth Appliance Group, Inc.",
"American Wallzone Supply, LLC",
"Atlanta Flooring Design Centers, Inc.",
"Atlanta West Cabinets, Inc.",
"Atlanta West Carpets, Inc",
"Automatic Fire Systems, Inc.",
"AV Pro Communications, LLC",
"Bama Concrete Products Co., Inc.",
"Bayles Land and Concrete",
"BDI, Inc.",
"Birmingham Construction Specialties Inc.",
"Blackman Plumbing LLC",
"Blind Source",
"Bobo Pest Control, Inc.",
"Boma Concrete, LLC",
"Brock Trim Company, Inc.",
"Buck Creek Concrete, LLC",
"C and C Construction Management, LLC",
"C. A. Murren & Sons, Inc",
"Capitol Materials, Inc",
"Champion Electric, LLC",
"Chris Williams, LLC",
"Colleys Landscape",
"Compass Construction, LLC",
"Counter Dimensions Inc.",
"CraneWorks, Inc.",
"Cutstone Company LLC",
"Dale of Alabama, Inc.",
"Daniel Allen English",
"Design Tile and Stone, Inc.",
"Dixie Acoustical Contractors, Inc.",
"Duncan Custom Gutter Co., Inc.",
"Favela Construction",
"Ferguson Enterprises, Inc.",
"Five Star Concrete Finishing, LLC",
"Flanagan Contracting, LLC",
"Front Row Media, LLC",
"Gadsden Lighting Showroom",
"Gomez Construction",
"Gomez Construction Inc.",
"Gould Electric, Inc.",
"Grayton Products, LLC",
"Guadalupe Castillo",
"H and O Drywall, Inc.",
"Higher Call Heating and Cooling, Inc.",
"Home Design Builders",
"Hurri-Bolt North America",
"Interior/Exterior Building Supply LP",
"Juan C. Luna",
"Juan De Dios Estrada Rivera",
"Kendrick, Tim",
"Kirkpatrick Concrete, Inc.",
"Kitchen Distributors, Inc.",
"L and L Construction, LLC",
"L and W Supply Corporation",
"Landscape Services, Inc.",
"Landscape Workshop, LLC",
"Layton's Glass & Supply",
"M & B Plumbing",
"Mailbox Specialists,Inc",
"Mario Vera",
"Marjam Supply of Alabama, LLC-Birmingham",
"Martinez Masonry",
"Masco Contractor Services Central,Inc.",
"Masterbrand Cabinets, Inc.",
"Maynor, Kurtis",
"McCain Carpet & Flooring, Inc.",
"MCS Construction, LLC",
"Mitchell Mechanical, LLC",
"MJR Drywall and Paint, LLC",
"Navarro Home Builders, LLC",
"NeedCo, Inc",
"Nick Daviston Insulation, Inc.",
"O.I.W. Inc.",
"Oak Mountain Building Supply, LLC",
"Olcott Real Estate LLC",
"Outdoor Lighting Perspectives, LLC",
"Over The Mountain Glass, Inc.",
"Parker & Sons Heating and Cooling, Inc.",
"Pepe's Construction, LLC",
"PFJ Roofing Specialties, Inc",
"Pro Flow, Inc.",
"Pro Form Concrete Construction, LLC",
"ProBuild Company, LLC",
"R Masonry, LLC",
"Sahara Construction, LLC",
"Saia, Steven",
"Schroeter's Lawn & Landscape, LLC",
"Service Department, LLC",
"Shelby Fence",
"Shelby Stain, LLC",
"Siano Appliance Distributors, Inc.",
"Slabs & Drives, LLC",
"Southern Care",
"Southern Clay Brick Company",
"Specified Design, LLC",
"SRS Distribution, Inc.",
"SRS Roofing Supply",
"Stan Smith Custom Tubs, Inc",
"Steelsafe Shelters",
"Stephen Fambrough",
"Structural Dimensions, Inc.",
"Superior Concrete Walls & Footings, Inc.",
"Surface One, Inc.",
"SWS Enterprises, Inc.",
"Synergy Stone, Inc.",
"T & C Construction",
"T and T Fireplace, LLC",
"The Mantel Shoppe LLC",
"Thomas Lowery Renovations and Repair, LLC",
"Tim Kendrick Construction",
"Top Electrical Services, Inc.",
"Truemark Metals",
"Truemark Metals, LLC",
"V & W Supply Company Inc.",
"Walter I. Helfinstine",
"Wayne Brantley Electric Co., Inc.",
"Wayne's Environmental Services, Inc.",
"William G. Hayes Construction, LLC",
"Xtreme Construction, LLC"]

NASHVILLE_SUPPLIERS = [
"1-JP Construction, LLC",
"Aguilar Masonry, LLC",
"Alabama Engineering Company, Inc",
"Alley- Cassetty Brick, Inc.",
"Allied Overhead Door",
"American Heating and Cooling, Inc.",
"Anchor Constructors, LLC",
"Arrowhead Survey, Inc.",
"Associated Materials, LLC",
"Austermiller Roofing",
"Bane, Kasey",
"Benchmark Plumbing, Inc.",
"Bozman Sign Co., Inc.",
"Brentwood Cabinets, LLC",
"Builders First Source - Atlantic Group, Inc.",
"Cambridge Landscaping, Inc.",
"Carter Hardware Co., Inc.",
"CES Services, LLC",
"Complete Exteriors, Inc.",
"Concrete Pump Partners, LLC",
"Cumberland Materials, Inc.",
"Custom Trim and Remodeling, LLC",
"Custom Trim, Inc.",
"Dale, Inc.",
"Daniels Welding Service",
"Dorris Construction Co., Inc.",
"Eagle Reclaimed Lumber",
"Elite Flooring, Inc.",
"Ferguson Enterprises, Inc.",
"Flanagan Contracting, LLC",
"G and M Plumbing Co., LLC",
"Garcia Concrete",
"Guevara Framing, LLC",
"H and H Land Surveying, Inc.",
"H.G. Classic Trim",
"Henley Supply Millwork, Inc.",
"Hermitage Electric Supply",
"HFR, Inc.",
"IMI-Tennessee Inc.",
"In and Out Framing",
"Insulation Solutions of Tn, Inc.",
"Intellistone, Inc.",
"Interactive Security Systems, LLC",
"J.W.C. Properties, Inc.",
"Jonathan Mitchell Watkins",
"KCS Construction, LLC",
"Kem-Max, Inc.",
"L and R Plumbing, LLC",
"Lojac Materials, Inc.",
"Madison Steel and Iron Works of Tn, Inc.",
"Markraft Cabinets, Inc.",
"Medusa Concrete Pumping Co., LLC",
"Metro Carpets, LLC",
"Mid American Concrete",
"Mid-TN Erosion & Sediment Control, Inc.",
"MSS Enterprises, LLC",
"N.R. Roofing, LLC",
"Northwest Plumbing Tn, Inc.",
"NS Construction Services, LLC",
"Outdoor Woodworks, LLC",
"Petersen and Sons, LLC",
"Planning, Design & Research Engineers, Inc.",
"Plumbing Distributors, Inc.",
"Ray McDaniel Cleaning Service",
"Real Green Solutions, LLC",
"Rogers Group, Inc.",
"Roofing Supply of Nashville,LLC",
"Rossi Family Services, Inc.",
"Sammons Waterproofing, Inc.",
"Sandhu Consultants International",
"Shoulders Excavating",
"Smyrna Ready Mix, LLC",
"Sortos Roofing and More, LLC",
"Structural Engineering and Inspections, LLC",
"Sun Splash Contracting",
"Tennessee Roofing Concepts, LLC",
"The Floor Specialist",
"The Porch Factory",
"Tobaldo, Jose A. Ayala",
"Wayne's Environmental Services, Inc.",
"Wilkerson and Son Masonry",
"William's Windows and More",
"Williamson County Ready Mix, Inc.",
"Willow Branch Landscaping-Outdoor Living, LLC"
]


TASK_CODES = ["Basement Foundation Walls",
"Blk Crwl or Slb Trndwn or Conc Trndwn",
"Builder Punch Work After Handoff Walk",
"Clean Interior, Windows, etc. 1",
"Cln Win, Int, etc. 2 After Bldr Punch Wk",
"Cornice After Brick",
"Cut Drives and Sidewalks",
"Deck Labor",
"Deck or Porch Material",
"Decorator Visit #2 Interior",
"Deliver Appliances",
"Deliver Brick",
"Deliver Footing/Slab Materials",
"Deliver Light Fixtures",
"Deliver Roofing Shingles POST Brick",
"Deliver Sheetrock",
"Deliver Shingles PRE Brick",
"Electrical Final Inspection",
"Electrical Rough",
"Electrical Rough Inspection",
"Electrical Trim - SetOut",
"Exterior Paint Final Coat",
"Exterior Paint Prime/1st Coat",
"Fence Install",
"Field & Production Manager Files Created",
"Final Building Inspection",
"Final Grade",
"Finish Sheetrock",
"Foundation Field File",
"Fourth interior clean",
"Frame Basement Walls",
"Frame Drop 1 - Order First Floor Walls,",
"Frame Drop 2 - 2nd Flr Walls, etc.",
"Frame Drop 3 - Order Roof System",
"Frame Drop 4 - Cornice & Siding",
"Frame Drop Basement Walls",
"Frame Rafters & Roof & Dry In",
"Frame Uppermost Floors & Walls",
"Frame Walls",
"Framing Rough Inspection",
"Generate Decorator 1 PO's",
"Grade Around Foundation - Backfill",
"Grade Around Slab Rough after Pour",
"Hang Sheetrock",
"Hardscaping for Yard",
"HVAC Final Inspection",
"HVAC Rough",
"HVAC Rough Inspection",
"HVAC Trim - SetOut",
"Install All Ceramic Tile",
"Install Bath Hardware",
"Install Batt Insulation",
"Install Blinds",
"Install Blown Insulation",
"Install Brick",
"Install Cabinets",
"Install Carpet",
"Install Cornice",
"Install Counter Tops",
"Install Doors & Windows",
"Install Doors, Trim, and Shutters",
"Install Fireplace",
"Install Fireplace Profile",
"Install Garage Door(s)",
"Install Gas Logs",
"Install Gutters & Downspouts",
"Install Hardwood Flooring",
"Install Lockout",
"Install Mailbox",
"Install Mantle",
"Install Metal Roofing",
"Install Mirrors",
"Install Porch Ceilings, Trim, Columns",
"Install Roof Flashing",
"Install Roofing",
"Install Roofing Post Brick",
"Install Screened Enclosures",
"Install Sewer-Home to Street/Septic",
"Install Shower Enclosure",
"Install Siding (non-Vinyl)",
"Install Stone",
"Install Tile Backsplash",
"Install Water Supply-Home to Street",
"Install Wire Shelving",
"Interior Paint Two Coats",
"Landscape Lighting",
"Landscaping",
"Order Block or Concrete for Trndwn",
"Order Cabinets",
"Order Concrete for Flat Work",
"Order Concrete for Footings",
"Order Concrete for Slab",
"Order Cornice After Brick",
"Order Ext Trim Porch Clgs Columms Etc",
"Order Exterior Doors & Windows",
"Order Fireplace Profile Materials (Brck)",
"Order Hardwood Flooring",
"Order Interior Trim and Doors",
"Order Lockout Materials",
"Order Plumbing Setout Materials",
"Order Shutters",
"Order Tile",
"Paint Interior Final",
"Phone and Cable Rough",
"Phone and Cable Setout",
"Plumbing Final Inspection",
"Plumbing Inspection Slab",
"Plumbing Rough",
"Plumbing Rough Inspection",
"Plumbing Trim - SetOut",
"Pour Drive and Walks",
"Pour Slab & Install Anchor Bolts",
"Pour Slab or Wall Footings",
"Prchsr Final Walk After Final Punch Work",
"Prep Slab Gravel and Steel for Pour",
"Pressure Wash Drive, Walks, etc.",
"Punch Final Work & Clean",
"Purchaser Framing Review",
"Rough Grading Check",
"Security, Speakers Setouts",
"Silt Fence Installed",
"Slab Formed and Boxed",
"Slab Forms Survey-if applicable",
"Slab Survey After Pour-No Frame W/Out",
"Sprinklers for All or Part Yard",
"Stake Lot",
"Termite Bait Stations",
"Third Interior Clean"]

